cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('product/<int:id>', views.product_detail, name='product_detail'),
    path('<int:id>', views.product_list, name='product_list_by_category'),

]

shopwebsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('orders/', include('orders.urls', namespace='orders')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models
from shop.models import Product

class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    count_product = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.count_product

shop/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    # objects = None
    name = models.CharField(max_length=200, db_index=True)
    description=models.TextField()
    # slug = models.SlugField(max_length=200, unique=True)
    # class Meta:
    #     ordering = ('name',)
    #     verbose_name = 'category'
    #     verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    # slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    # created_date = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # class Meta:
    #     ordering = ('name',)
    #     index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address',
                  'postal_code', 'city']

cart/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
    cart.add(product=product,
             quantity=cd['quantity'],
             update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    print(cart)
    return render(request, 'cart/detail.html', {'cart': cart})

orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         count_product=item['quantity'])
            # Очищаем корзину.
            cart.clear()
            return render(request,
                          'orders/order/created.html',
                          {'order': order})
    else:
        form = OrderCreateForm()
    return render(request,
                  'orders/order/create.html',
                  {'cart': cart, 'form': form})

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product


# Create your views here.
def product_list(request, id=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if id:
        category = get_object_or_404(Category, id=id)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {'category': category,
                                                      'categories': categories,
                                                      'products': products})


# def product_detail(request, id):
#     product = get_object_or_404(Product, id=id, available=True)
#     return render(request, 'shop/product/detail.html', {'product': product})



from cart.forms import CartAddProductForm


def product_detail(request, id):
    product = get_object_or_404(Product, id=id, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}Your shopping cart{% endblock %}
{% block content %}
<h1>Your shopping cart</h1>
<table>
    <thead>
    <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit price</th>
        <th>Price</th>
    </tr>
    </thead>
    <tbody>
        {% for item in cart %}
<!--    {{item}}-->
<!--        {% with product=item.product %}-->
            {{product}}
            <tr>
                <td>
                    <a href="{% url 'shop:product_detail' id=item.product.id %}">
                        <img src="{% if item.product.image %}{{ item.product.image.url }}
                        {% else %}{% static 'img/no_image.jpg' %}{% endif %}">
                    </a>
                </td>
                <td>{{ item.product.name }}</td>
                <td>{{ item.quantity }}</td>
                <td><a href="{% url 'cart:cart_remove' product.id%}">Remove</a></td>
                <td>${{ item.price }}</td>
                <td>${{ item.total_price }}</td>
            </tr>
<!--        {% endwith %}-->
    {% endfor %}
    <tr>
        <td>Total</td>
        <td colspan="4"></td>
        <td>${{ cart.get_total_price }}</td>
    </tr>
    </tbody>
</table>
<p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="button light">Continue shopping</a>
    <a href="{% url 'orders:order_create' %}" class="button">Checkout</a>
</p>
{% endblock %}

orders/templates/orders/order/create.html
{% extends "shop/base.html" %}
{% block title %}
Checkout
{% endblock %}
{% block content %}
<h1>Checkout</h1>
<div class="order-info">
    <h3>Your order</h3>
    <ul>
        {% for item in cart %}
        <li>
            {{ item.quantity }}x {{ item.product.name }}
            <span>${{ item.total_price }}</span>
        </li>
        {% endfor %}
    </ul>
    <p>Total: ${{ cart.get_total_price }}</p>
</div>
<form action="." method="post" class="order-form">
    {{ form.as_p }}
    <p><input type="submit" value="Place order"></p>
    {% csrf_token %}
</form>
{% endblock %}

orders/templates/orders/order/created.html
{% extends "shop/base.html" %}
{% block title %}
Thank you
{% endblock %}
{% block content %}
<h1>Thank you</h1>
<p>Your order has been successfully completed. Your order number is
    <strong>{{ order.id }}</strong>.</p>
{% endblock %}

shop/templates/shop/base.html
{% load static %}
<!--<!DOCTYPE html>-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Магазин {% endblock %} </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'shop:product_list' %}">Магазин</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'shop:product_list' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                Про магазин
              </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link" href="#">
                Контакти
              </a>
            </li>
          </ul>
                <a class="btn btn-primary" href="{% url 'cart:cart_detail' %}">
                    <div > Корзина </div>
                    <span>
                     {% with total_items=cart|length %}
                     {% if cart|length > 0 %}
                        {{ total_items }}
                     {% else %}
                        0
                     {% endif %}
                     {% endwith %}
                    </span>
                </a>
          </div>
      </div>
    </nav>
<div class="container">
    <div class="row m-2">
    {% block content %}{% endblock %}
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}
    {% static 'img/no_image.jpg' %}{% endif %}">
    <h1>{{ product.name }}</h1>
    <h2>
        <!-- АБО описати в моделі функцію get_absolute_url    <a href="{{ product.category.get_absolute_url }}">{{product.category }}</a> -->
        <a href="{% url 'shop:product_list_by_category' id=product.category.id %}">{{product.category }}</a>
    </h2>
    <p>${{ product.description }}</p>
    {{ product.description|linebreaks }}
    <p>${{ product.price }}</p>
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <input type="submit" value="Add to cart">
    </form>

</div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if category %}
category.name
{% else %}
Продукти
{% endif %}
{% endblock %}
{% block content %}
<div class="col-6 col-md-3">
    <h6>Категорії</h6>
    <ul>
        <li {% if not category %} class="selected" {% endif %}>
            <a href="{% url 'shop:product_list' %}">Всі</a>
        </li>
        {% for cat in categories %}
        <li>
            <a href="{{cat.get_absolute_url}}">{{cat.name}}</a>
        </li>
        {% endfor %}
    </ul>
</div>
<div class="col-md-9">
    <div class="container">
        <div class="row m-2">
            {% for product in products %}
            <div class="col-4">
                 <div class="card m-2">
                    <a href="{% url 'shop:product_detail' product.id %}">
                        <img src="{% if product.image %} {{product.image.url}}{% else%}{% static 'img/no_image.jpg'%}{% endif %}"
                             class="card-img-top" >
                    </a>

                    <div class="card-body">
                        <a href="{% url 'shop:product_detail' product.id %}">
                            <h5 class="card-title"> {{product.name}}</h5>
                        </a>
                        <p class="card-text"> {{product.description}}</p>
                        <p class="card-text">{{product.price}} грн. </p>
                        <a href="{% url 'cart:cart_add' product.id %}" class="btn btn-primary">Додати</a>
                    </div>
                 </div>
            </div>
            {% endfor %}


        </div>
    </div>
    <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
            {% if page.has_previous %}
            <li class="page-item">
              <a  href="?page={{page.previous_page_number}}" aria-label="Previous">
                <span aria-hidden="true">Попередня</span>
              </a>
            </li>
            {% endif%}
              <li class="page-item">
                  <span aria-hidden="true">
                      &nbsp; стор. {{page.number}} із {{page.paginator.num_pages}}&nbsp;
                  </span>
              </li>
            {% if page.has_next %}
              <li class="page-item">
              <a  href="?page={{page.next_page_number}}" aria-label="Next">
                <span aria-hidden="true"> Наступна </span>
              </a>
            </li>
              {% endif%}
          </ul>
        </nav>
</div>
{% endblock %}